- ocd_backend/extractors/ibabs.py
- ocd_backend/sources/utrecht.json
to be able to get more information.
> Implement paging in the iBabs extractor

- ocd_backend/extractors/ibabs.py
- ocd_backend/items/ibabs_meeting.py
- ocd_backend/utils/ibabs.py
> Extract document for reports in iBabs. Fixes #9

- ocd_backend/extractors/cwc.py
- ocd_backend/items/cwc.py
- ocd_backend/settings.py
- ocd_backend/sources/utrecht.json
Implements videotulen for Company Webcast (Utrecht, specifically)
> Cwc videotulen

- ocd_backend/items/ibabs_meeting.py
- ocd_backend/utils/ibabs.py
So that we can have the actual description of promises (for example)
> Add toelichting veld.

- ocd_backend/extractors/goapi.py
- ocd_backend/items/goapi_committee.py
- ocd_backend/items/goapi_meeting.py
- ocd_backend/items/goapi_meetingitem.py
- ocd_backend/sources/doetinchem.json
- ocd_backend/sources/goirle.json
- ocd_backend/sources/noordoostpolder.json
- ocd_backend/sources/steenbergen.json
- ocd_frontend/settings.py
Code was based on existing iBabs and GO scraper.
The code seems to be working, though it hasn't been fully tested yet.
> Gemeente Oplossingen API implementation

- Dockerfile
- ocd_backend/utils/pdf.py
- requirements.txt
Is approx. 30 times faster than a pure-python implementation such as pdfminer. The lib is installed when building dockerfile
> [IMP] Pdfparser using poppler on linux

- ocd_backend/Dockerfile
- ocd_backend/enrichers/media_enricher/__init__.py
- ocd_backend/extractors/__init__.py
- ocd_backend/requirements.txt
- ocd_frontend/Dockerfile
- ocd_frontend/requirements.txt
It appears some older packages contain vulnerabilities, this PR should solve those.
> Upgrading backend requirements for CVE vulnerabilities

- ocd_backend/items/ibabs_meeting.py
Forgot to add this to IBabsReportItem.
> Added has_organization_name to IBabsReportItem

- ocd_backend/loaders/elasticsearch.py
- ocd_backend/sources/ori.go.yaml
- ocd_backend/sources/ori.ibabs.yaml
- ocd_backend/sources/ori.notubiz.yaml
- ocd_backend/sources/ori.parlaeus.yaml
- ocd_backend/sources/ori.pg.yaml
- ocd_backend/sources/osi.go.yaml
- ocd_backend/sources/osi.gv.yaml
- ocd_backend/sources/osi.ibabs.yaml
> Switch to using the Elasticsearch Upsert Loader to avoid data loss

- ocd_backend/sources/osi.notubiz.yaml
> Added province Overijssel in new source file: osi.notubiz

- ocd_backend/extractors/allmanak.py
- ocd_backend/extractors/goapi.py
- ocd_backend/extractors/gv.py
- ocd_backend/extractors/ibabs.py
- ocd_backend/extractors/notubiz.py
- ocd_backend/extractors/staticfile.py
- ocd_backend/models/definitions/org.py
- ocd_backend/pipeline.py
- ocd_backend/settings.py
- ocd_backend/sources/ori.go.yaml
- ocd_backend/sources/ori.ibabs.yaml
- ocd_backend/sources/ori.notubiz.yaml
- ocd_backend/sources/ori.parlaeus.yaml
- ocd_backend/sources/ori.pg.yaml
- ocd_backend/sources/osi.go.yaml
- ocd_backend/sources/osi.gv.yaml
- ocd_backend/sources/osi.ibabs.yaml
- ocd_backend/sources/osi.notubiz.yaml
- ocd_backend/transformers/organizations.py
- Changed `KAFKA_ENABLED` to an environment variable;
- Added `homepage` and `email` to municipality and province resources;
- Differentiated usage of `sitename`: it is now split into `ibabs_sitename` and `source_name` (currently not used).
> Milestone 1.3.2

- deployment/endpoints/production.yaml
- deployment/endpoints/staging.yaml
Same as PR #244 but now directly in this repo so I can commit and merge.
> Allow more ES endpoints

- ocd_backend/sources/ori.ibabs.yaml
- ocd_backend/transformers/ibabs_report.py
Smarter determination of start_date, title and description for ibabs reports. Fixes #328
> IBabs report update

- ocd_backend/alembic/versions/5b2ac6d04808_add_prop_float_column_to_property.py
- ocd_backend/models/definitions/meeting.py
- ocd_backend/models/postgres_database.py
- ocd_backend/models/postgres_models.py
- ocd_backend/models/serializers.py
- ocd_backend/transformers/ibabs_meeting.py
- ocd_backend/utils/ibabs.py
- tests/ocd_backend/utils/test_ibabs.py
**WARNING: CONTAINS DATABASE MIGRATION!!!**
* Add prop_float column to Property table
* Changed agenda item position from IntegerProperty to FloatProperty; added raw_position as StringProperty
* Add translation to float or raw string value for iBabs agenda item position
Fixes #338
> Fix for ibabs agenda item positions

- ocd_backend/sources/ori.go.yaml
> Add West Betuwe (GOAPI)

- ocd_backend/enrichers/__init__.py
- ocd_backend/enrichers/text_enricher/tasks/waaroverheid.py
- ocd_backend/extractors/__init__.py
- ocd_backend/extractors/allmanak.py
- ocd_backend/extractors/database.py
- ocd_backend/extractors/ggm.py
- ocd_backend/extractors/goapi.py
- ocd_backend/extractors/gv.py
- ocd_backend/extractors/ibabs.py
- ocd_backend/extractors/notubiz.py
- ocd_backend/extractors/parlaeus.py
- ocd_backend/extractors/staticfile.py
- ocd_backend/loaders/delta.py
- ocd_backend/loaders/elasticsearch.py
- ocd_backend/models/model.py
- ocd_backend/models/postgres_database.py
- ocd_backend/pipeline.py
- ocd_backend/tasks.py
- ocd_backend/transformers/gedeputeerdestaten.py
- ocd_backend/transformers/goapi_meeting.py
- ocd_backend/transformers/ibabs_meeting.py
- ocd_backend/transformers/ibabs_report.py
- ocd_backend/transformers/notubiz_meeting.py
- ocd_backend/utils/file_parsing.py
- ocd_backend/utils/http.py
- ocd_backend/utils/ibabs.py
- ocd_backend/utils/misc.py
- tests/ocd_backend/utils/test_ibabs.py
- version.py
* Small fixup for `translate_position` on iBabs AgendaItems;
* Fix for iBabs extractor raising `StopIteration` causing the pipeline to fail;
* Refactored logging and error message code;
* Added source definition key to more error messages; 
* Switched logging to use f-strings
> Bugfix version 1.7.2

- ocd_backend/extractors/parlaeus.py
- ocd_backend/sources/ori.ibabs.yaml
- ocd_backend/sources/ori.notubiz.yaml
- ocd_backend/sources/ori.parlaeus.yaml
* Improved Parlaeus error handling
* Switched Maastricht from Notubiz to Parlaeus
* Added Eindhoven (Parlaeus)
* Switched Leeuwarden from Notubiz to iBabs
> Add and switch municipalities

- README.md
@jurrian can you verify if we can add these?
> Add parlaeus and tweede kamer to supported sources in readme

- maintenance_guide.md
> Add maintenance guide

- maintenance_guide.md
- ocd_backend/sources/ori.ibabs.yaml
- ocd_backend/sources/osi.gv.yaml
- ocd_backend/sources/owi.ibabs.yaml
- ocd_backend/sources/owi.notubiz.yaml
- ocd_backend/transformers/allmanak_organization.py
- Heb de basis source files van de OSI items gekopieerd, municipality extractor uitgezet (weet niet of deze ergens voor vereist is - maar we hebben de items IMO niet in de zoekindex nodig) #447 @breyten zou jij kunnen kijken of ik hier dingen mis?
- Duplicate entry voor Zuid-Holland verwijderd #449
> Waterschappen #447
